[package]
name = "shader_compilation"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
glob = "0.3.0"
log = "0.4.11"
simplelog = { version = "0.9.0", features = ["termcolor"] }